# @name RegisterUser
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "user":{
    "username": "Jacob",
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

###
# @name LoginUser
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "user":{
    "email": "jake@jake.jake",
    "password": "prueba"
  }
}

###
@token = {{LoginUser.response.body.user.token}}

###
# @name UpdateUser
PUT http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user":{
    "email": "jake@jake.jake",
    "username": "jacob",
    "password": "prueba",
    "bio": "I like to skateboard",
    "image": "https://i.stack.imgur.com/xHWG8.jpg"
  }
}

###
# @name GetCurrentUser
GET http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer {{token}}


###
# @name GetAllArticles
GET http://localhost:8080/api/articles
Content-Type: application/json
Authorization: Bearer {{token}}